# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.box = "nrel/CentOS-6.5-x86_64"
	config.vm.hostname = "puppet"
	# config.vm.network "forwarded_port", guest: 80, host: 8082
	config.vm.network "private_network", ip: "10.10.10.2"
	config.vm.provision "shell", path: "script.sh"
end
# this Vagrant will generate a CentOS6.5 machine with puppet server installed
